### ISSUE TITLE
Output is the same as the input

### ISSUE THREAD

**Issue by foala** [CAFS-bioinformatics/LR_Gapcloser#6]
Hello,
I ran your LR_Gapcloser on my scaffolds using my PacBio raw data.
The fasta output (Iteration3 folder) is exactly like the input.
however, I get the following error in error log file
/apps/modules-4.2.0/init/bash: line 37: /usr/bin/tclsh: No such file or directory

please help.
Thank you

**Comment by ViriatoII** [comment]
No answers? I also have same output as input!
